spring.application.name=backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/lojavirtualnfc
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=2713
spring.http.cors.enabled=true
spring.http.cors.origins=*

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contatohappytimebrinquedos@gmail.com
spring.mail.password=RePPYt1m3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


aws.access.key=DO00MVPPJNJ8MEQH4CN9
aws.secret.key=k/YrrPeiTtIlsVNX7JslzM51j1oRD3JHAnDTJuLWIMc
aws.s3.region=sfo3
aws.s3.bucket=virtualnfcbucket
# O endpoint deve ser o host sem o nome do bucket no início
aws.s3.endpoint=https://sfo3.digitaloceanspaces.com